# Generated by Django 3.1 on 2021-04-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='donation_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
