# Generated by Django 3.1 on 2021-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210408_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='donation_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
