# Generated by Django 3.1 on 2021-04-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210408_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_total',
            field=models.IntegerField(default=0),
        ),
    ]
