# Generated by Django 3.1 on 2021-04-08 22:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20210409_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='petition_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='fundraiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 22, 6, 30, 410808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='article_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='main.article'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 22, 6, 30, 414248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='current_signature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petition',
            name='goal_signature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petitions'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
