# Generated by Django 3.1 on 2021-04-08 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210409_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 15, 43, 743256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 15, 43, 748182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petitions'),
        ),
    ]
