# Generated by Django 3.1 on 2021-04-09 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210409_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 5, 22, 59, 615897, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 5, 22, 59, 619662, tzinfo=utc)),
        ),
    ]
