# Generated by Django 3.1 on 2021-04-08 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210409_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 16, 22, 723371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 16, 22, 727454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='current_signature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petition',
            name='goal_signature',
            field=models.IntegerField(default=0),
        ),
    ]
