# Generated by Django 3.1 on 2021-04-08 20:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_auto_20210409_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 16, 45, 71773, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 16, 45, 75751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
