# Generated by Django 3.1 on 2021-04-09 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210409_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 9, 16, 26, 613871, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 9, 16, 26, 617486, tzinfo=utc)),
        ),
    ]
