# Generated by Django 3.1 on 2021-04-08 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210409_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='donate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 43, 14, 268334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 43, 14, 272427, tzinfo=utc)),
        ),
    ]
