# Generated by Django 3.1 on 2021-04-08 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210409_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 54, 14, 857911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 20, 54, 14, 862007, tzinfo=utc)),
        ),
    ]
